TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
#DB += EL1002.template EL1002.substitutions
DB += EL1124.template EL1124.substitutions
DB += EL1808.template EL1808.substitutions
DB += EL2124.template EL2124.substitutions
DB += EL2798.template EL2798.substitutions
DB += EL2808.template EL2808.substitutions
DB += EL3008.template EL3008.substitutions
DB += EL3068.template EL3068.substitutions
DB += EL3164.template EL3164.substitutions
DB += EL3314.template EL3314.substitutions
DB += EL4008.template EL4008.substitutions
DB += EL4038.template EL4038.substitutions
DB += EL9505.template EL9505.substitutions

DB += ek9000_status.db

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

